item/urls.py
from django.urls import path

from item.views import ItemListView, ItemDetailView

urlpatterns = [
    path(r'', ItemListView.as_view(), name='home'),
    path(r'item/<int:pk>/', ItemDetailView.as_view(), name='item_detail'),
]

stripeShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path('', include('order.urls')),
    path('', include('other.urls')),
]

order/models.py
from django.db import models


class Order(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    total = models.DecimalField(verbose_name='Order total', max_digits=15, decimal_places=2)
    total_with_promos = models.DecimalField(verbose_name='Order total with discount', max_digits=15, decimal_places=2)

    class Meta:
        verbose_name_plural = 'Orders'
        verbose_name = 'Order'


class OrderItem(models.Model):
    order = models.ForeignKey('Order',
                              verbose_name='Order',
                              related_name='order_items',
                              on_delete=models.CASCADE)
    item = models.ForeignKey('item.Item', verbose_name='Item (Product)', on_delete=models.PROTECT)
    quantity = models.DecimalField(verbose_name='Quantity', max_digits=11, decimal_places=2)
    total_with_taxes = models.DecimalField(verbose_name='Total with Taxes', max_digits=15, decimal_places=2)

    class Meta:
        verbose_name_plural = 'Order elements'
        verbose_name = 'Order element'


class DiscountToOrder(models.Model):
    """For bond Order with Promo Codes and Discount Coupons"""
    created_at = models.DateTimeField(auto_now_add=True)
    order = models.ForeignKey('Order',
                              verbose_name='Order',
                              related_name='discount_bundles',
                              on_delete=models.PROTECT)
    promo = models.ForeignKey('other.PromoCode',
                              verbose_name='Promo',
                              related_name='order_bundles',
                              on_delete=models.PROTECT,
                              blank=True, null=True)
    coupon = models.ForeignKey('other.DiscountCoupon',
                               verbose_name='Coupon',
                               related_name='order_bundles',
                               on_delete=models.PROTECT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block extra_css %}

    {% endblock extra_css %}
    <title>{% block title %}Home{% endblock title %}</title>
</head>
<body>
<div>
    <ul>
        <li><a href="{% url 'home' %}">Products page</a></li>
        <li><a href="{% url 'order_list' %}">Orders page</a></li>
    </ul>
    <h2>Cart</h2>
    <h3>US Dollars</h3>
    <table border="1">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Self Price</th>
            <th>Price with Taxes</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody class="card_body" id="cart_body_usd">
        {% for cart_item in cart %}
            {% if cart_item.currency == 'usd' %}
                <tr>
                    <td>{{ cart_item.id }}</td>
                    <td>{{ cart_item.name }}</td>
                    <td>{{ cart_item.price }}$</td>
                    <td>{{ cart_item.price_with_taxes }}$</td>
                    <td>{{ cart_item.quantity }}</td>
                    <td>{{ cart_item.total }}$</td>
                    <td>
                        <button class="add_to_cart_btn" type="button" data-item-id="{{ cart_item.id }}">
                            +
                        </button>
                        <button class="sub_from_cart_btn" type="button" data-item-id="{{ cart_item.id }}">
                            -
                        </button>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7"><a href="{% url 'create_order_from_cart' 'usd' %}">Create order</a></td>
            </tr>
        </tfoot>
    </table>
    <h3>Russian Rubles</h3>
    <table border="1">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Self Price</th>
            <th>Price with Taxes</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody class="card_body" id="cart_body_rub">
        {% for cart_item in cart %}
            {% if cart_item.currency == 'rub' %}
                <tr>
                    <td>{{ cart_item.id }}</td>
                    <td>{{ cart_item.name }}</td>
                    <td>{{ cart_item.price }}₽</td>
                    <td>{{ cart_item.price_with_taxes }}₽</td>
                    <td>{{ cart_item.quantity }}</td>
                    <td>{{ cart_item.total }}₽</td>
                    <td>
                        <button class="add_to_cart_btn" type="button" data-item-id="{{ cart_item.id }}">
                            +
                        </button>
                        <button class="sub_from_cart_btn" type="button" data-item-id="{{ cart_item.id }}">
                            -
                        </button>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7"><a href="{% url 'create_order_from_cart' 'usd' %}">Create order</a></td>
            </tr>
        </tfoot>
    </table>
    <h3>Promo Codes</h3>
    <table border="1">
        <thead>
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Percent Off</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody id="cart_body_promo">
        {% for promo in promos %}
            <tr>
                <td>{{ promo.code }}</td>
                <td>{{ promo.name }}</td>
                <td>{{ promo.percent_off }} %</td>
                <td>
                    <button class="deactivate_promo_btn" type="button" onclick="deactivatePromo('{{ promo.code }}')">
                        Deactivate
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3"><input type="text" id="add_promo_input"></td>
            <td>
                <button type="button" onclick="activatePromo()" id="add_promo_button">Add Promo</button>
            </td>
        </tr>
        </tfoot>
    </table>
</div>
{% block content %}
{% endblock content %}

{% block extra_js %}

{% endblock extra_js %}
<script>
    let addItemToCart = document.getElementsByClassName('add_to_cart_btn')
    let subItemFromCart = document.getElementsByClassName('sub_from_cart_btn')

    for (let addElem of addItemToCart) {
        addElem.addEventListener('click', function (e) {
            // Create a new Checkout Session using the server-side endpoint
            // Redirect to Stripe Session Checkout
            fetch(`/cart/add/${e.target.getAttribute('data-item-id')}/`, {method: 'GET'})
                .then(response => response.json())
                .then(data => updateCartBody(data.cart))
        });
    }

    for (let subElem of subItemFromCart) {
        subElem.addEventListener('click', function (e) {
            // Create a new Checkout Session using the server-side endpoint
            // Redirect to Stripe Session Checkout
            fetch(`/cart/sub/${e.target.getAttribute('data-item-id')}/`, {method: 'GET'})
                .then(response => response.json())
                .then(data => updateCartBody(data.cart))
        });
    }

    function activatePromo() {
        let promoInput = document.getElementById('add_promo_input')
        if (promoInput.value !== '') {
            fetch(`/promo/activate/${promoInput.value}/`, {method: 'GET'})
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'Ok') {
                        updatePromoBody(data.promo)
                    } else alert(data.message)
                })
        }
        promoInput.value = ''
    }

    function deactivatePromo(promoCode) {
        fetch(`/promo/deactivate/${promoCode}/`, {method: 'GET'})
            .then(response => response.json())
            .then(data => {
                if (data.status === 'Ok') {
                    updatePromoBody(data.promo)
                } else alert(data.message)
            })
    }

    function updatePromoBody(promos) {
        console.log(promos)
        let promoBody = document.getElementById('cart_body_promo')
        let _template = ``
        for (let promo_code in promos) {
            let promo = promos[promo_code]
            _template += `
            <tr>
                <td>${promo.code}</td>
                <td>${promo.name}</td>
                <td>${promo.percent_off} %</td>
                <td>
                    <button class="deactivate_promo_btn" type="button" onclick="deactivatePromo('${promo.code}')">
                        Deactivate
                    </button>
                </td>
            </tr>
            `
        }

        promoBody.innerHTML = _template
    }

    function updateCartBody(cartItems) {
        let cartBodyUSD = document.getElementById('cart_body_usd')
        let cartBodyRUB = document.getElementById('cart_body_rub')
        let _template_usd = ``
        let _template_rub = ``
        for (let cartItem of cartItems) {
            if (cartItem.currency === 'usd') {
                _template_usd += `
                <tr>
                    <td>${cartItem.id}</td>
                    <td>${cartItem.name}</td>
                    <td>${cartItem.price}$</td>
                    <td>${cartItem.price_with_taxes}$</td>
                    <td>${cartItem.quantity}</td>
                    <td>${cartItem.total}$</td>
                    <td>
                        <button class="add_to_cart_btn" type="button" data-item-id="${cartItem.id}">
                            +
                        </button>
                        <button class="sub_from_cart_btn" type="button" data-item-id="${cartItem.id}">
                            -
                        </button>
                    </td>
                </tr>
                `
            } else if (cartItem.currency === 'rub') {
                _template_rub += `
                <tr>
                    <td>${cartItem.id}</td>
                    <td>${cartItem.name}</td>
                    <td>${cartItem.price}₽</td>
                    <td>${cartItem.price_with_taxes}₽</td>
                    <td>${cartItem.quantity}</td>
                    <td>${cartItem.total}₽</td>
                    <td>
                        <button class="add_to_cart_btn" type="button" data-item-id="${cartItem.id}">
                            +
                        </button>
                        <button class="sub_from_cart_btn" type="button" data-item-id="${cartItem.id}">
                            -
                        </button>
                    </td>
                </tr>
                `
            }
        }

        cartBodyRUB.innerHTML = _template_rub
        cartBodyUSD.innerHTML = _template_usd

        for (let addElem of addItemToCart) {
            if (addElem.matches('tbody  tr  td  button'))
                addElem.addEventListener('click', function (e) {
                    // Create a new Checkout Session using the server-side endpoint
                    // Redirect to Stripe Session Checkout
                    fetch(`/cart/add/${e.target.getAttribute('data-item-id')}/`, {method: 'GET'})
                        .then(response => response.json())
                        .then(data => updateCartBody(data.cart))
                });
        }

        for (let subElem of subItemFromCart) {
            if (subElem.matches('tbody  tr  td  button'))
                subElem.addEventListener('click', function (e) {
                    // Create a new Checkout Session using the server-side endpoint
                    // Redirect to Stripe Session Checkout
                    fetch(`/cart/sub/${e.target.getAttribute('data-item-id')}/`, {method: 'GET'})
                        .then(response => response.json())
                        .then(data => updateCartBody(data.cart))
                });
        }
    }
</script>
</body>
</html>